FROM python:3.12.7

WORKDIR /my-gpt-rag

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./backend/main.py .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

